spring:
  profiles:
    active: dev

jasypt:
  encryptor:
    bean: jasyptEncryptor

jwt:
  secret: ENC(Td1Bn+vflHJE40VjINaGpgisHP0MBdY5oQ+aZdJy9uWLNlQinfTG983inwWWKBP5lfRdmVIz768CU6DIt7oFHJWFP8r1p3JMHhkwb1UhaXriwRmrDRNZ+u3cqnYRvH3LqEY1hI7ANQlIU6Wxt5mH8vPsagzBVUPW6pcAThVMyDY=)

encrypt:
  password: ${JASYPT_PASSWORD}