spring:
  profiles:
    active: dev

jasypt:
  encryptor:
    bean: jasyptEncryptor

jwt:
  secret: ENC(my/tqsn3UFtBynfEk8NUgkFbm0KypK4tavGdtDgRjp2DJ1Gh29LtGDZ7hVyW8u9DwQv8HaOyAc5w1c1ZLhUxT+R0S7eYkCTL4nwDKIQr73XWc2G1nADFMLhqeoBJV6JUTZtX9HP+bsnUgLZE5+LQ7n0cvRZXOKknHb4t1CxhLXU=)

encrypt:
  password: ${JASYPT_PASSWORD}