spring:

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(QL9P55yeqSGSRPeFFsm8HGqiZyTEzd/XWrOx0LrHmV8vsbKwI9ruvBd665et6qQMF9irqA9941qqeOBlzN+LeQ==)
    password: ENC(wdUvFe2rxidFUvpBc2Nv/i8gu3dY1fCSMoUTSLYedrrdQwN13ffsEwp2N7IuMNUJa3ZcNqtKdWvBpKmGDMC68g==)
    properties:
      mail:
        smtp:
          debug: true
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true

  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: ENC(rCp++HbH119YE4QzRIoPOonW6j+LBb4pBt/vXfhL8SDi2AKq0hHvP52u/K23qY6evmDzKnw34K9TPEAOBZRtqA==)
      credentials:
        access-key: ENC(/aDHbQDVYIm4zT9BEODxZPf6zg59qRzBmdpwL4QVF/OOFTJ0kRBH0yoIGCKefn6Ta7djOZt0YloPQmUbgZwMtQ==)
        secret-key: ENC(ELwfo1GKsusD3LJpwPPUZfI0tGtwMHGAn+CnUGhzPNOw74r7zSHKZwI605spkm/NfhIdKe5HKeI68hRKQVpC67wM3lhZ8t9rZa8WuOEK1VE=)

  jpa:
    open-in-view: false

  # 소셜 로그인 설정(구글)
  security:    
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile

jasypt:
  encryptor:
    bean: jasyptEncryptor

jwt:
  secret: ENC(Td1Bn+vflHJE40VjINaGpgisHP0MBdY5oQ+aZdJy9uWLNlQinfTG983inwWWKBP5lfRdmVIz768CU6DIt7oFHJWFP8r1p3JMHhkwb1UhaXriwRmrDRNZ+u3cqnYRvH3LqEY1hI7ANQlIU6Wxt5mH8vPsagzBVUPW6pcAThVMyDY=)

bannabe:
  default-profile-image: ENC(GKEZ+q1NesSCsYhn5m/2VAxsHhtA7EWsn4Bj4B57MKRCMi/Ag6G0BkfxW3QPd0TF9YYRC+8sKek4zY07/z1ea0dKXhhiLGRn3du/WtiqcMhwuWaI8fHlHkimD+dE/9reDRIjzJ9mfQC2BfaHS2rP7XtmFzS3XdJnXgO1omcqkNw=)
  payment:
    api-key: ENC(wFicTPhVO8Jezk+5Lfn7ECuJnIrZ1nSlmxz1i3M3TNiah+EsnHjm+ALgx49jQjXlLjOvYAm8xkx4UYuXMgs2vIbafOQfyttgt2CJz5KmAcw=)
    secret-key: ENC(qIwNHKFFiZZAk3hCSfXG3U164hXF1mNj7Ln8oVY7JKvxuyLIqwduosF7RIIGHDrbj4SxsN2wtbLXqd5wp6FqZoAYmzVG9BiLfKFi2i6ymUM=)

encrypt:
  password: ${JASYPT_PASSWORD}