openapi: 3.0.1
info:
  title: Bannabe API
  description: Bannabe API 문서
  version: 0.0.1
servers:
- url: http://localhost:8080
tags: []
paths:
  /v1/stations:
    get:
      tags:
      - RentalStationController
      summary: 전체 대여 스테이션 조회 API
      description: 전체 대여 스테이션 조회 API
      operationId: rental_station_controller_test/get_all_rental_station
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1-stations486549215"
              examples:
                rental_station_controller_test/get_all_rental_station:
                  value: "{\r\n  \"success\" : true,\r\n  \"message\" : \"요청이 성공적으\
                    로 처리되었습니다.\",\r\n  \"data\" : {\r\n    \"stations\" : [ {\r\n\
                    \      \"name\" : \"테스트 스테이션0\",\r\n      \"address\" : \"서울시\
                    \ 강남구\",\r\n      \"latitude\" : 37.514575,\r\n      \"longitude\"\
                    \ : 127.049555,\r\n      \"status\" : \"OPEN\",\r\n      \"businessTime\"\
                    \ : \"09:00 ~ 18:00\",\r\n      \"grade\" : \"FIRST\",\r\n   \
                    \   \"stationId\" : 7\r\n    }, {\r\n      \"name\" : \"테스트 스테\
                    이션1\",\r\n      \"address\" : \"서울시 강남구\",\r\n      \"latitude\"\
                    \ : 37.514575,\r\n      \"longitude\" : 127.049555,\r\n      \"\
                    status\" : \"OPEN\",\r\n      \"businessTime\" : \"09:00 ~ 18:00\"\
                    ,\r\n      \"grade\" : \"FIRST\",\r\n      \"stationId\" : 8\r\
                    \n    }, {\r\n      \"name\" : \"테스트 스테이션2\",\r\n      \"address\"\
                    \ : \"서울시 강남구\",\r\n      \"latitude\" : 37.514575,\r\n      \"\
                    longitude\" : 127.049555,\r\n      \"status\" : \"OPEN\",\r\n\
                    \      \"businessTime\" : \"09:00 ~ 18:00\",\r\n      \"grade\"\
                    \ : \"FIRST\",\r\n      \"stationId\" : 9\r\n    }, {\r\n    \
                    \  \"name\" : \"테스트 스테이션3\",\r\n      \"address\" : \"서울시 강남구\"\
                    ,\r\n      \"latitude\" : 37.514575,\r\n      \"longitude\" :\
                    \ 127.049555,\r\n      \"status\" : \"OPEN\",\r\n      \"businessTime\"\
                    \ : \"09:00 ~ 18:00\",\r\n      \"grade\" : \"FIRST\",\r\n   \
                    \   \"stationId\" : 10\r\n    }, {\r\n      \"name\" : \"테스트 스\
                    테이션4\",\r\n      \"address\" : \"서울시 강남구\",\r\n      \"latitude\"\
                    \ : 37.514575,\r\n      \"longitude\" : 127.049555,\r\n      \"\
                    status\" : \"OPEN\",\r\n      \"businessTime\" : \"09:00 ~ 18:00\"\
                    ,\r\n      \"grade\" : \"FIRST\",\r\n      \"stationId\" : 11\r\
                    \n    }, {\r\n      \"name\" : \"테스트 스테이션5\",\r\n      \"address\"\
                    \ : \"서울시 강남구\",\r\n      \"latitude\" : 37.514575,\r\n      \"\
                    longitude\" : 127.049555,\r\n      \"status\" : \"OPEN\",\r\n\
                    \      \"businessTime\" : \"09:00 ~ 18:00\",\r\n      \"grade\"\
                    \ : \"FIRST\",\r\n      \"stationId\" : 12\r\n    }, {\r\n   \
                    \   \"name\" : \"테스트 스테이션6\",\r\n      \"address\" : \"서울시 강남구\
                    \",\r\n      \"latitude\" : 37.514575,\r\n      \"longitude\"\
                    \ : 127.049555,\r\n      \"status\" : \"OPEN\",\r\n      \"businessTime\"\
                    \ : \"09:00 ~ 18:00\",\r\n      \"grade\" : \"FIRST\",\r\n   \
                    \   \"stationId\" : 13\r\n    }, {\r\n      \"name\" : \"테스트 스\
                    테이션7\",\r\n      \"address\" : \"서울시 강남구\",\r\n      \"latitude\"\
                    \ : 37.514575,\r\n      \"longitude\" : 127.049555,\r\n      \"\
                    status\" : \"OPEN\",\r\n      \"businessTime\" : \"09:00 ~ 18:00\"\
                    ,\r\n      \"grade\" : \"FIRST\",\r\n      \"stationId\" : 14\r\
                    \n    }, {\r\n      \"name\" : \"테스트 스테이션8\",\r\n      \"address\"\
                    \ : \"서울시 강남구\",\r\n      \"latitude\" : 37.514575,\r\n      \"\
                    longitude\" : 127.049555,\r\n      \"status\" : \"OPEN\",\r\n\
                    \      \"businessTime\" : \"09:00 ~ 18:00\",\r\n      \"grade\"\
                    \ : \"FIRST\",\r\n      \"stationId\" : 15\r\n    }, {\r\n   \
                    \   \"name\" : \"테스트 스테이션9\",\r\n      \"address\" : \"서울시 강남구\
                    \",\r\n      \"latitude\" : 37.514575,\r\n      \"longitude\"\
                    \ : 127.049555,\r\n      \"status\" : \"OPEN\",\r\n      \"businessTime\"\
                    \ : \"09:00 ~ 18:00\",\r\n      \"grade\" : \"FIRST\",\r\n   \
                    \   \"stationId\" : 16\r\n    }, {\r\n      \"name\" : \"테스트 스\
                    테이션10\",\r\n      \"address\" : \"서울시 강남구\",\r\n      \"latitude\"\
                    \ : 37.514575,\r\n      \"longitude\" : 127.049555,\r\n      \"\
                    status\" : \"OPEN\",\r\n      \"businessTime\" : \"09:00 ~ 18:00\"\
                    ,\r\n      \"grade\" : \"FIRST\",\r\n      \"stationId\" : 17\r\
                    \n    }, {\r\n      \"name\" : \"테스트 스테이션11\",\r\n      \"address\"\
                    \ : \"서울시 강남구\",\r\n      \"latitude\" : 37.514575,\r\n      \"\
                    longitude\" : 127.049555,\r\n      \"status\" : \"OPEN\",\r\n\
                    \      \"businessTime\" : \"09:00 ~ 18:00\",\r\n      \"grade\"\
                    \ : \"FIRST\",\r\n      \"stationId\" : 18\r\n    }, {\r\n   \
                    \   \"name\" : \"테스트 스테이션12\",\r\n      \"address\" : \"서울시 강남\
                    구\",\r\n      \"latitude\" : 37.514575,\r\n      \"longitude\"\
                    \ : 127.049555,\r\n      \"status\" : \"OPEN\",\r\n      \"businessTime\"\
                    \ : \"09:00 ~ 18:00\",\r\n      \"grade\" : \"FIRST\",\r\n   \
                    \   \"stationId\" : 19\r\n    }, {\r\n      \"name\" : \"테스트 스\
                    테이션13\",\r\n      \"address\" : \"서울시 강남구\",\r\n      \"latitude\"\
                    \ : 37.514575,\r\n      \"longitude\" : 127.049555,\r\n      \"\
                    status\" : \"OPEN\",\r\n      \"businessTime\" : \"09:00 ~ 18:00\"\
                    ,\r\n      \"grade\" : \"FIRST\",\r\n      \"stationId\" : 20\r\
                    \n    }, {\r\n      \"name\" : \"테스트 스테이션14\",\r\n      \"address\"\
                    \ : \"서울시 강남구\",\r\n      \"latitude\" : 37.514575,\r\n      \"\
                    longitude\" : 127.049555,\r\n      \"status\" : \"OPEN\",\r\n\
                    \      \"businessTime\" : \"09:00 ~ 18:00\",\r\n      \"grade\"\
                    \ : \"FIRST\",\r\n      \"stationId\" : 21\r\n    }, {\r\n   \
                    \   \"name\" : \"테스트 스테이션15\",\r\n      \"address\" : \"서울시 강남\
                    구\",\r\n      \"latitude\" : 37.514575,\r\n      \"longitude\"\
                    \ : 127.049555,\r\n      \"status\" : \"OPEN\",\r\n      \"businessTime\"\
                    \ : \"09:00 ~ 18:00\",\r\n      \"grade\" : \"FIRST\",\r\n   \
                    \   \"stationId\" : 22\r\n    }, {\r\n      \"name\" : \"테스트 스\
                    테이션16\",\r\n      \"address\" : \"서울시 강남구\",\r\n      \"latitude\"\
                    \ : 37.514575,\r\n      \"longitude\" : 127.049555,\r\n      \"\
                    status\" : \"OPEN\",\r\n      \"businessTime\" : \"09:00 ~ 18:00\"\
                    ,\r\n      \"grade\" : \"FIRST\",\r\n      \"stationId\" : 23\r\
                    \n    }, {\r\n      \"name\" : \"테스트 스테이션17\",\r\n      \"address\"\
                    \ : \"서울시 강남구\",\r\n      \"latitude\" : 37.514575,\r\n      \"\
                    longitude\" : 127.049555,\r\n      \"status\" : \"OPEN\",\r\n\
                    \      \"businessTime\" : \"09:00 ~ 18:00\",\r\n      \"grade\"\
                    \ : \"FIRST\",\r\n      \"stationId\" : 24\r\n    }, {\r\n   \
                    \   \"name\" : \"테스트 스테이션18\",\r\n      \"address\" : \"서울시 강남\
                    구\",\r\n      \"latitude\" : 37.514575,\r\n      \"longitude\"\
                    \ : 127.049555,\r\n      \"status\" : \"OPEN\",\r\n      \"businessTime\"\
                    \ : \"09:00 ~ 18:00\",\r\n      \"grade\" : \"FIRST\",\r\n   \
                    \   \"stationId\" : 25\r\n    }, {\r\n      \"name\" : \"테스트 스\
                    테이션19\",\r\n      \"address\" : \"서울시 강남구\",\r\n      \"latitude\"\
                    \ : 37.514575,\r\n      \"longitude\" : 127.049555,\r\n      \"\
                    status\" : \"OPEN\",\r\n      \"businessTime\" : \"09:00 ~ 18:00\"\
                    ,\r\n      \"grade\" : \"FIRST\",\r\n      \"stationId\" : 26\r\
                    \n    } ]\r\n  }\r\n}"
  /v1/payments/calculate:
    post:
      tags:
      - PaymentController
      summary: 결제 금액 계산 API
      description: 결제 금액 계산 API
      operationId: payment_controller_test/calculate_amount
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/v1-stations486549215"
            examples:
              payment_controller_test/calculate_amount:
                value: "{\r\n  \"rentalItemToken\" : \"RI_YZzamqA8Ep\",\r\n  \"rentalTime\"\
                  \ : 2\r\n}"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1-stations486549215"
              examples:
                payment_controller_test/calculate_amount:
                  value: "{\r\n  \"success\" : true,\r\n  \"message\" : \"요청이 성공적으\
                    로 처리되었습니다.\",\r\n  \"data\" : {\r\n    \"rentalItemToken\" : \"\
                    RI_YZzamqA8Ep\",\r\n    \"pricePerHour\" : 1000,\r\n    \"rentalTime\"\
                    \ : 2,\r\n    \"amount\" : 2000\r\n  }\r\n}"
      security:
      - bearerAuthJWT: []
  /v1/payments/checkout-url:
    get:
      tags:
      - PaymentController
      summary: 결제창 호출 URL 조회 API
      description: 결제창 호출 URL 조회 API
      operationId: payment_controller_test/get_checkout_url
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1-stations486549215"
              examples:
                payment_controller_test/get_checkout_url:
                  value: "{\r\n  \"success\" : true,\r\n  \"message\" : \"요청이 성공적으\
                    로 처리되었습니다.\",\r\n  \"data\" : {\r\n    \"checkoutUrl\" : \"http://localhost:8080/v1/payments/checkout\"\
                    \r\n  }\r\n}"
      security:
      - bearerAuthJWT: []
  /v1/payments/confirm:
    post:
      tags:
      - PaymentController
      summary: 결제 승인 API
      description: 결제 승인 API
      operationId: payment_controller_test/confirm_payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/v1-stations486549215"
            examples:
              payment_controller_test/confirm_payment:
                value: "{\r\n  \"paymentKey\" : \"paymentKey\",\r\n  \"amount\" :\
                  \ 1000,\r\n  \"orderId\" : \"orderId\"\r\n}"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1-stations486549215"
              examples:
                payment_controller_test/confirm_payment:
                  value: "{\r\n  \"success\" : true,\r\n  \"message\" : \"요청이 성공적으\
                    로 처리되었습니다.\",\r\n  \"data\" : {\r\n    \"rentalHistoryToken\"\
                    \ : \"RH_WAcyV8XIhL\"\r\n  }\r\n}"
      security:
      - bearerAuthJWT: []
  /v1/rentals/{rentalItemToken}:
    get:
      tags:
      - RentalController
      summary: 대여물품 조회 API
      description: 대여물품 조회 API
      operationId: rental_controller_test/get_rental_item_token
      parameters:
      - name: rentalItemToken
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1-stations486549215"
              examples:
                rental_controller_test/get_rental_item_token:
                  value: "{\r\n  \"success\" : true,\r\n  \"message\" : \"요청이 성공적으\
                    로 처리되었습니다.\",\r\n  \"data\" : {\r\n    \"name\" : \"65W 충전기\"\
                    ,\r\n    \"price\" : 1000,\r\n    \"currentStationName\" : \"테\
                    스트 스테이션\"\r\n  }\r\n}"
      security:
      - bearerAuthJWT: []
  /v1/stations/{stationId}:
    get:
      tags:
      - RentalStationController
      summary: 대여 스테이션 상세정보 조회 API
      description: 대여 스테이션 상세정보 조회 API
      operationId: rental_station_controller_test/get_rental_station_detail
      parameters:
      - name: stationId
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1-stations486549215"
              examples:
                rental_station_controller_test/get_rental_station_detail:
                  value: "{\r\n  \"success\" : true,\r\n  \"message\" : \"요청이 성공적으\
                    로 처리되었습니다.\",\r\n  \"data\" : {\r\n    \"rentalItems\" : [ {\r\
                    \n      \"itemTypeId\" : 3,\r\n      \"name\" : \"65W 충전기\",\r\
                    \n      \"image\" : \"test-image.png\",\r\n      \"category\"\
                    \ : \"CHARGER\",\r\n      \"stock\" : 10\r\n    }, {\r\n     \
                    \ \"itemTypeId\" : 4,\r\n      \"name\" : \"100W 충전기\",\r\n  \
                    \    \"image\" : \"test-image.png\",\r\n      \"category\" : \"\
                    CHARGER\",\r\n      \"stock\" : 10\r\n    } ]\r\n  }\r\n}"
  /v1/oauth2/login/{provider}:
    post:
      tags:
      - OAuth2Controller
      summary: OAuth2 인증 요청 API
      description: OAuth2 인증 요청 API
      operationId: o_auth2_controller_test/kakao_login_success
      parameters:
      - name: provider
        in: path
        description: ""
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/v1-stations486549215"
            examples:
              o_auth2_controller_test/kakao_login_success:
                value: "{\r\n  \"accessToken\" : \"accessToken\",\r\n  \"deviceToken\"\
                  \ : \"deviceToken\"\r\n}"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1-stations486549215"
              examples:
                o_auth2_controller_test/kakao_login_success:
                  value: "{\r\n  \"success\" : true,\r\n  \"message\" : \"요청이 성공적으\
                    로 처리되었습니다.\",\r\n  \"data\" : {\r\n    \"accessToken\" : \"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiUk9MRSI6IlJPTEVfVVNFUiIsImlhdCI6MTc0MjU3NzkyMSwiZXhwIjoxNzQyNTc5NzIxfQ.YUwibAavgPfpb3Uyrtv8wIQcsddoKTRvRNw5hYjRkjyExGbYfBbG1iSL_Nf5rRD5ojB3YAWAR5PG203KvkSAJg\"\
                    ,\r\n    \"refreshToken\" : \"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiUk9MRSI6IlJPTEVfVVNFUiIsImlhdCI6MTc0MjU3NzkyMSwiZXhwIjoxNzQzMTgyNzIxfQ.aap2Cx6Wij4VoG8k3qHFLNGAPFxaK0U8hRrNFz3qNEOikQMp3nz354TWIjjQjHJ3s07orW4t7g1bpzFKXqNqrg\"\
                    \r\n  }\r\n}"
  /v1/rentals/success/{rentalHistoryToken}:
    get:
      tags:
      - RentalController
      summary: 대여내역 조회 API
      description: 대여내역 조회 API
      operationId: rental_controller_test/get_rental_history_info
      parameters:
      - name: rentalHistoryToken
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1-stations486549215"
              examples:
                rental_controller_test/get_rental_history_info:
                  value: "{\r\n  \"success\" : true,\r\n  \"message\" : \"요청이 성공적으\
                    로 처리되었습니다.\",\r\n  \"data\" : {\r\n    \"totalAmount\" : 1000,\r\
                    \n    \"itemName\" : \"65W 충전기\",\r\n    \"rentalTime\" : 1,\r\
                    \n    \"rentalStationName\" : \"테스트 스테이션\"\r\n  }\r\n}"
      security:
      - bearerAuthJWT: []
  /v1/stations/{stationId}/bookmark:
    post:
      tags:
      - RentalStationController
      summary: 스테이션 북마크 API
      description: 스테이션 북마크 API
      operationId: rental_station_controller_test/bookmark_rental_station
      parameters:
      - name: stationId
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1-stations486549215"
              examples:
                rental_station_controller_test/bookmark_rental_station:
                  value: "{\r\n  \"success\" : true,\r\n  \"message\" : \"요청이 성공적으\
                    로 처리되었습니다.\",\r\n  \"data\" : { }\r\n}"
      security:
      - bearerAuthJWT: []
  /v1/stations/{stationId}/items/{itemTypeId}:
    get:
      tags:
      - RentalStationController
      summary: 대여 물품 상세정보 조회 API
      description: 대여 물품 상세정보 조회 API
      operationId: rental_station_controller_test/get_rental_item_detail
      parameters:
      - name: stationId
        in: path
        description: ""
        required: true
        schema:
          type: string
      - name: itemTypeId
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1-stations486549215"
              examples:
                rental_station_controller_test/get_rental_item_detail:
                  value: "{\r\n  \"success\" : true,\r\n  \"message\" : \"요청이 성공적으\
                    로 처리되었습니다.\",\r\n  \"data\" : {\r\n    \"name\" : \"65W 충전기\"\
                    ,\r\n    \"image\" : \"test-image.png\",\r\n    \"category\" :\
                    \ \"CHARGER\",\r\n    \"description\" : \"테스트 설명\",\r\n    \"\
                    price\" : 1000,\r\n    \"stock\" : 10\r\n  }\r\n}"
components:
  schemas:
    v1-stations486549215:
      type: object
  securitySchemes:
    bearerAuthJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
