name: Push Workflow (Build & Test)

on:
  push:
    branches:
      - feature/**
      - fix/**
      - chore/**
      - refactor/**
      - test/**

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read